name: Test WARP connection
on:
  workflow_dispatch:
  schedule:
    - cron: '09 04 * * 6'
  push:
    branches: [main, release/*]
    paths: ['*.sh', '*.yml']
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Install WARP
        run: ./install.sh
      - name: Connect WARP
        run: ./connect.sh
      - name: Check connection
        run: ./status.sh
      - name: Disconnect, delete registration
        run: warp-cli --accept-tos disconnect && warp-cli --accept-tos registration delete
