name: test WARP connection
on:
  workflow_dispatch:
  schedule:
    - cron: '54 09 * * *'
  push:
    branches: [main, release/*]
    paths: ['*.sh', '*.yml']
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install WARP
        run: ./install.sh
      - name: Connect WARP
        run: ./connect.sh
      - name: Check connection
        run: ./status.sh
